// SPDX-License-Identifier: MIT

import Foundation
import SupervisorCore

/// `hearth proxy-setup`: generate a ready-to-run authenticating reverse proxy
/// config (Caddy) for the runner, from this machine's actual Hearth config.
/// Proxying inference traffic is a job for a battle-tested proxy, not something
/// Hearth reimplements; this makes the documented pattern turnkey: a Caddyfile
/// with a real random bearer token, the runner's real port, and the tailnet
/// address when one is present, plus the exact commands to run it.
enum ProxySetupCLI {
    static func run(_ args: [String]) -> Never {
        guard args.isEmpty || (args.count == 2 && args[0] == "--output" && !args[1].hasPrefix("--")) else {
            print("Usage: hearth proxy-setup [--output DIRECTORY]")
            exit(1)
        }
        let loaded = ConfigStore.load(from: AppPaths.configFile, createDefaultIfMissing: false)
        guard !loaded.createdDefault else {
            print("No configuration exists. Run `hearth setup` or save settings in Preferences first.")
            exit(1)
        }
        let blocking = loaded.blockingDiagnostics()
        guard blocking.isEmpty else {
            FileHandle.standardError.write(Data((blocking.map(\.message).joined(separator: "\n") + "\n").utf8))
            exit(1)
        }
        let config = loaded.config
        var outputDirectory = FileManager.default.currentDirectoryPath
        if let flagIndex = args.firstIndex(of: "--output"), args.indices.contains(flagIndex + 1) {
            outputDirectory = args[flagIndex + 1]
        }

        let bind = NetworkInterfaces.tailnetIPv4() ?? "YOUR-TAILSCALE-OR-LAN-ADDRESS"
        let token = randomToken()
        let upstreamHost = probeHost(for: config.host)
        guard !upstreamHost.isEmpty, upstreamHost.utf8.allSatisfy({
            (48...57).contains($0) || (65...90).contains($0) || (97...122).contains($0)
                || [UInt8(46), 45, 58].contains($0)
        }), (1...65_535).contains(config.clientPort) else {
            FileHandle.standardError.write(Data("Hearth: invalid client endpoint; correct host and port first.\n".utf8))
            exit(1)
        }
        let content = caddyfile(bindAddress: bind, proxyPort: 8443,
                                runnerPort: config.clientPort, token: token, runnerHost: upstreamHost)

        let url = URL(fileURLWithPath: outputDirectory).appendingPathComponent("Caddyfile.hearth")
        guard SecureFile.write(Data(content.utf8), to: url) else {
            FileHandle.standardError.write(Data(
                "Hearth: could not securely write \(url.path). Check folder permissions.\n".utf8))
            exit(1)
        }

        let commandPath = "'" + url.path.replacingOccurrences(of: "'", with: "'\\''") + "'"
        print("""
        Hearth proxy-setup
          wrote \(url.path) (mode 600; it contains the bearer token)

        It gates every request on a bearer token and forwards to the runner at
        \(config.clientEndpoint). To serve it:

          brew install caddy
          caddy validate --adapter caddyfile --config \(commandPath)
          caddy run --adapter caddyfile --config \(commandPath)

        (or copy it to $(brew --prefix)/etc/Caddyfile and `brew services start
        caddy` so launchd keeps the proxy alive too.)

        Clients then call:

          curl -H "Authorization: Bearer \(token)" http://\(urlAuthorityHost(for: bind)):8443\(config.makeRunner().readinessEndpoint.path)

        \(bind == "YOUR-TAILSCALE-OR-LAN-ADDRESS"
            ? "No Tailscale interface was found; edit the bind address in the file to your private address first."
            : "The listener binds to this Mac's Tailscale address. Keep access restricted by your tailnet policy.")
        This HTTP example relies on Tailscale encryption. Configure HTTPS when
        using another network, so the bearer token is encrypted in transit.
        Keep the runner itself on 127.0.0.1; the proxy is the only thing that
        should face the network. docs/reverse-proxy.md has the background and an
        nginx variant.
        """)
        exit(0)
    }

    /// Pure generator, mirroring deploy/Caddyfile.example with real values.
    static func caddyfile(bindAddress: String, proxyPort: Int, runnerPort: Int, token: String, runnerHost: String = "127.0.0.1") -> String {
        """
        # Generated by `hearth proxy-setup`. An authenticating reverse proxy in
        # front of the runner: every request must carry the bearer token below,
        # and the runner itself stays on 127.0.0.1. See docs/reverse-proxy.md.

        http://\(urlAuthorityHost(for: bindAddress)):\(proxyPort) {
        \tbind \(bindAddress)
        \t@authorized header Authorization "Bearer \(token)"

        \thandle @authorized {
        \t\treverse_proxy \(urlAuthorityHost(for: runnerHost)):\(runnerPort)
        \t}

        \t# Anything without the right token gets nothing useful.
        \trespond "Unauthorized" 401
        }
        """
    }

    private static func randomToken() -> String {
        (0..<24).map { _ in String(format: "%02x", UInt8.random(in: 0...255)) }.joined()
    }
}
