// SPDX-License-Identifier: MIT

import Foundation
import SupervisorCore

/// `hearth proxy-setup`: generate a ready-to-run authenticating reverse proxy
/// config (Caddy) for the runner, from this machine's actual Hearth config.
/// Proxying inference traffic is a job for a battle-tested proxy, not something
/// Hearth reimplements; this makes the documented pattern turnkey: a Caddyfile
/// with a real random bearer token, the runner's real port, and the tailnet
/// address when one is present, plus the exact commands to run it.
enum ProxySetupCLI {
    static func run(_ args: [String]) -> Never {
        let config = ConfigStore.load().config
        var outputDirectory = FileManager.default.currentDirectoryPath
        if let flagIndex = args.firstIndex(of: "--output"), args.indices.contains(flagIndex + 1) {
            outputDirectory = args[flagIndex + 1]
        }

        let bind = NetworkInterfaces.tailnetIPv4() ?? "YOUR-TAILSCALE-OR-LAN-ADDRESS"
        let token = randomToken()
        let content = caddyfile(bindAddress: bind, proxyPort: 8443,
                                runnerPort: config.port, token: token)

        let url = URL(fileURLWithPath: outputDirectory).appendingPathComponent("Caddyfile.hearth")
        do {
            try Data(content.utf8).write(to: url)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
        } catch {
            FileHandle.standardError.write(Data(
                "Hearth: could not write \(url.path): \(error.localizedDescription)\n".utf8))
            exit(1)
        }

        print("""
        Hearth proxy-setup
          wrote \(url.path) (mode 600; it contains the bearer token)

        It gates every request on a bearer token and forwards to the runner at
        127.0.0.1:\(config.port). To serve it:

          brew install caddy
          caddy validate --config \(url.path)
          caddy run --config \(url.path)

        (or copy it to $(brew --prefix)/etc/Caddyfile and `brew services start
        caddy` so launchd keeps the proxy alive too.)

        Clients then call:

          curl -H "Authorization: Bearer \(token)" http://\(bind):8443/api/version

        \(bind == "YOUR-TAILSCALE-OR-LAN-ADDRESS"
            ? "No Tailscale interface was found; edit the bind address in the file to your private address first."
            : "The bind address is this Mac's Tailscale address, so only your tailnet can reach it.")
        Keep the runner itself on 127.0.0.1; the proxy is the only thing that
        should face the network. docs/reverse-proxy.md has the background and an
        nginx variant.
        """)
        exit(0)
    }

    /// Pure generator, mirroring deploy/Caddyfile.example with real values.
    static func caddyfile(bindAddress: String, proxyPort: Int, runnerPort: Int, token: String) -> String {
        """
        # Generated by `hearth proxy-setup`. An authenticating reverse proxy in
        # front of the runner: every request must carry the bearer token below,
        # and the runner itself stays on 127.0.0.1. See docs/reverse-proxy.md.

        \(bindAddress):\(proxyPort) {
        \t@authorized header Authorization "Bearer \(token)"

        \thandle @authorized {
        \t\treverse_proxy 127.0.0.1:\(runnerPort)
        \t}

        \t# Anything without the right token gets nothing useful.
        \trespond "Unauthorized" 401
        }
        """
    }

    private static func randomToken() -> String {
        (0..<24).map { _ in String(format: "%02x", UInt8.random(in: 0...255)) }.joined()
    }
}
